добавил статью про gitbash
Yandex-Practicum/extra-content pull request #7
Opened 2024-02-07 11:50 UTC by MedvedevNik

2024-02-07 12:07 UTC, pa7lux requested changes

2024-02-07 12:07 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +
Можем добавить подраздел "Что такое Bash"? В нём коротко обозначить проблему разных терминалов в виндовс, и в остальных системах. Потом сказать, почему надо учить именно Bash (потому что мы изучаем веб, а подавляющее число серверов в вебе — это линукс с башем, поэтому команды для него запомнить важнее). И подвести к тому, что на виндовс можно установить тулзу, которая позволит использовать синтаксис баша — гитбаш

2024-02-07 12:07 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +Git Bash стал необходимым инструментом для разработчиков из-за того, что Git работает лучше на UNIX-подобных системах, а не на Windows. Git Bash обеспечивает полноценное взаимодействие с Git и позвол
Ребята не знают, что такое UNIX-подобные системы. Это тоже надо сказать во введении

2024-02-07 12:07 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +Чтобы загрузить проект на свой Git-репозиторий через Git Bash, выполните следующие шаги:
Сделал бы подводку о том, что возможно раньше ребята сталкивались с загрузкой кода на гитхаб через какие-то графические интерфейсы. Но изначально гит был создан как консольная программа, то есть вводишь команды в терминал — они выполняются. Это полезный навык, программисту часто приходится работать с серверами удалённо, через терминал, а в нём нет графического интерфейса

2024-02-07 12:07 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +### Как использовать Git в Visual Studio Code?
мне кажется, это в другую статью какую-то надо перенести

2024-02-07 12:07 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +**Git Bash** - это специальная командная строка, которая позволяет управлять Git на компьютере с операционной системой Windows. Этот инструмент позволяет разработчикам легко работать с Git, делать ко
убрал бы акцент с гита, сместил бы его на Bash. Git подал бы как приятный пример. Рассказал бы, что называется так, потому что создавали чтоб удобнее работать именно с гитом

2024-02-07 12:07 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +Git Bash и Git в VS Code - это два мощных инструмента для работы с Git на Windows. Git Bash предоставляет полный набор команд Git через командную строку, а Git в VS Code позволяет управлять Git прямо
Думаю, всё же надо оставить только про гитбаш, и заключение тоже переписать из принципа равноправия задач "Гит на виндовс" и "Баш на виндовс"

2024-02-07 12:09 UTC, pa7lux commented
Огромное спасибо за статью. Выше несколько комментариев и предложений, как сделать её лучше и ближе к теме.
Хочется сосредоточиться именно на Bash, а гит разобрать как крутой способ его применения и вообще полезность.

Статью про VSCode тулзы лучше сделать отдельной

2024-02-07 12:36 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +url: /video/tools/gitbash/final.mov
этого видео нет в репо, битая ссылка роняет сборку. если видео очень нужно и оно длинное, можно вставить html-тег с айфреймом youtube

2024-02-09 14:43 UTC, ber-p commented on content/tools/gitbash-tools.md
> +Git Bash стал необходимым инструментом для разработчиков из-за того, что Git работает лучше на UNIX-подобных системах, а не на Windows. Git Bash обеспечивает полноценное взаимодействие с Git и позвол
может, вообще опустить этот момент?

2024-02-09 14:43 UTC, ber-p commented on content/tools/gitbash-tools.md
> +### Установить Git Bash очень просто:
строку можно удалить, пусть сразу идут шаги 1, 2, 3...

2024-02-09 14:43 UTC, ber-p commented on content/tools/gitbash-tools.md
> +## Как установить Git Bash на Windows
давай сделаем "Как установить Git Bash на Windows за 4 шага"

2024-02-09 14:43 UTC, ber-p commented on content/tools/gitbash-tools.md
> +
Давай тут добавим строчку: "В этой статье мы разберем, что такое Git Bash, как его установить на Windows и как с его помощью загрузить проект на GitHub"

2024-02-09 14:56 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +### Установить Git Bash очень просто:
строку нельзя удалять, потому что так работает маркдаун

2024-02-09 15:10 UTC, pa7lux reviewed
круто, статья стала намного лучше, мы уже близки

2024-02-09 15:10 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +В прошлом, загрузка кода на GitHub часто выполнялась через графические интерфейсы. Однако, Git был изначально создан как консольная программа, где пользователь вводит команды в терминал, и они выполн
Вы могли раньше встречаться с загрузкой кода на GitHub через графические интерфейсы: Github Desktop, сам сайт github.com или встроенные плагины для редактора кода. Но Git был изначально создан как консольная программа, где пользователь вводит команды в терминал, и они выполняются. Этот подход, хоть и может показаться сложным на первый взгляд, на самом деле предоставляет более гибкий и мощный способ управления компьютером.
```suggestion
В прошлом, загрузка кода на GitHub часто выполнялась через графические интерфейсы. Однако, Git был изначально создан как консольная программа, где пользователь вводит команды в терминал, и они выполняются. Этот подход, хоть и может показаться сложным на первый взгляд, на самом деле предоставляет более гибкий и мощный способ управления кодом.
```

2024-02-09 15:12 UTC, MedvedevNik commented on content/tools/gitbash-tools.md
> +### Установить Git Bash очень просто:
@pa7lux, @ber-p могу сделать чисто текстом без заголовка 3 уровня

2024-02-09 15:20 UTC, pa7lux commented on content/tools/gitbash-tools.md
> +### Установить Git Bash очень просто:
да дождись редакторских правок, Полина принесёт. Там это тоже будет. Скорее всего подача текста в целом немного поменяется

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +Сегодня в этой статье мы разберем:
замена на "В этой статье мы разберём:"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +- [ ] что такое Git Bash
тут должно быть "что такое Bash"?

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +**Bash (Bourne Again SHell)** - это специальная командная строка, которая позволяет управлять компьютером с помощью текстовых команд. Она используется в некоторых операционных системах, например, Lin
замена на "Bash (Bourne Again SHell) — это специальная", тире надо

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +## Как установить Git Bash на Windows за 4 шага
заменить 4 на "четыре"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +1. Перейдите на [официальный сайт Git](https://git-scm.com/downloads).
замена на "Перейди"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +2. Скачайте установочный файл для Windows.
замена на "Скачай"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +3. Запустите установку и следуйте инструкциям мастера установки.
"Запусти" и "следуй"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +4. После установки откройте Git Bash из меню Пуск или щелкните правой кнопкой мыши на папке в проводнике и выберите "Git Bash Here".
"открой" и "щёлкни правой кнопкой мыши на папке в проводнике и выбери «Git Bash Here»" (кавычки-елочки тоже важны)

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +Чтобы загрузить проект на свой Git-репозиторий через Git Bash, выполните следующие шаги:
"выполни"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +1. Откройте Git Bash и перейдите в папку с вашим проектом с помощью команды
замена строки на "Открой Git Bash и перейди в папку с твоим проектом с помощью команды"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +2. Инициализируйте новый Git-репозиторий с помощью команды
"Инициализируй"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +3. Добавьте все файлы проекта в индекс с помощью команды
"Добавь"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +4. Сделайте коммит с вашими изменениями с помощью команды
"Сделай коммит с твоими"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +5. Создайте новый удаленный репозиторий на GitHub или GitLab.
замена на "Создай новый удалённый репозиторий на GitHub или GitLab.
Свяжи локальный репозиторий с удалённым с помощью команды"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +6. Загрузите изменения на удаленный репозиторий с помощью команды
"Загрузи изменения на удалённый" (буква ё важна)

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +
дописать: "Ниже скринкаст о том, как выгрузить проект на гитхаб."

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +В данной статье мы с вами разобрали
"В данной статье мы разобрали:"

2024-02-14 10:50 UTC, ber-p commented on content/tools/gitbash-tools.md
> +Изучение Bash и использование Git Bash помогут вам эффективно управлять вашими проектами, особенно если вы работаете с веб-разработкой. Знание командной строки и умение работать с Git открывают новые
замена на "Изучение Bash и использование Git Bash помогут тебе эффективно управлять проектами. Знание командной строки и умение работать с Git открывают новые возможности и делают процесс разработки более удобным и эффективным."

2024-02-15 08:07 UTC, merged